apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoshi-gateway
  labels:
    app: hoshi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoshi-gateway
  template:
    metadata:
      name: hoshi-gateway
      labels:
        app: hoshi-gateway
    spec:
      containers:
        - name: hoshi-gateway
          image: ghcr.io/syfxlin/hoshi-note:hoshi-gateway
          imagePullPolicy: IfNotPresent
          command:
            - java
            - -jar
            - /app/hoshi-gateway-1.0-SNAPSHOT.jar
          ports:
            - name: hoshi-gateway
              containerPort: 7000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hoshi-gateway
spec:
  selector:
    app: hoshi-gateway
  ports:
    - name: hoshi-gateway
      port: 7000
      nodePort: 37000
  type: NodePort
