server:
  port: ${PORT:8000}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  redis:
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}
    sentinel:
      master: mymaster
      nodes: ${REDIS_SENTINEL}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_FILE_SIZE:20MB}
minio:
  url: ${MINIO_URL}
  bucket: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
pexels:
  token: ${PEXELS_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
springdoc:
  swagger-ui:
    path: /actuator/swagger-ui.html
  api-docs:
    path: /actuator/openapi
