apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: hoshi-note
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: hoshi-services
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: hoshi-services
                  key: RABBITMQ_PASSWORD
          ports:
            - name: rabbitmq
              containerPort: 5672
            - name: rabbitmq-manage
              containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
              subPath: rabbitmq
      restartPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: data-volume
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: hoshi-note
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      nodePort: 30672
    - name: rabbitmq-manage
      port: 15672
      nodePort: 30673
  type: NodePort
