version: 13
jobs:
- name: registry
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    image: docker:latest
    commands:
    - cp misc/deploy/registry/Dockerfile .
    - ''
    - docker build -t ghcr.io/syfxlin/hoshi-note:registry .
    - ''
    - echo "@secret:GITHUB_PACKAGES_TOKEN@" | docker login ghcr.io -u syfxlin --password-stdin
    - ''
    - docker push ghcr.io/syfxlin/hoshi-note:registry
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
