### 注册
POST http://localhost:8000/register
Accept: application/json
Content-Type: application/json

{
    "username": "test",
    "password": "password",
    "nickname": "Test",
    "email": "email@ixk.me",
    "status": 1,
    "avatar": null
}

### 登录
POST http://localhost:8000/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username=admin&password=password

> {% client.global.set("token", response.headers.valueOf("X-Auth-Token")); %}

### Token 登录
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

token=1706b23c-daaa-4ff5-bd50-54643d63aa7e

> {% client.global.set("token", response.headers.valueOf("X-Auth-Token")); %}

### 获取当前登录的用户信息
GET http://localhost:8000/api/users
Accept: application/json
Authorization: Bearer {{token}}

### 获取所有用户
GET http://localhost:8000/api/admin/users?page=0&size=1&sort=id,desc
Accept: application/json
Authorization: Bearer {{token}}

### 添加用户
POST http://localhost:8000/api/admin/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test",
    "password": "password",
    "nickname": "Test",
    "email": "email@ixk.me",
    "status": 1,
    "avatar": null
}

> {% client.global.set("test_user_id", response.body.data.id); %}

### 更新用户
PUT http://localhost:8000/api/admin/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": {{test_user_id}},
  "nickname": "Test1"
}

### 添加用户权限
POST http://localhost:8000/api/admin/users/role
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": {{test_user_id}},
  "roles": ["TEST"]
}

### 修改用户权限
PUT http://localhost:8000/api/admin/users/role
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": {{test_user_id}},
  "roles": ["USER"]
}

### 删除用户权限
DELETE http://localhost:8000/api/admin/users/role?id={{test_user_id}}&roles=USER
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### 删除用户
DELETE http://localhost:8000/api/admin/users?id={{test_user_id}}
Accept: application/json
Authorization: Bearer {{token}}

### 获取所有权限
GET http://localhost:8000/api/admin/roles
Accept: application/json
Authorization: Bearer {{token}}

### 添加一个权限
POST http://localhost:8000/api/admin/roles
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "TEST",
    "description": "测试权限",
    "status": 1
}

### 更新权限
PUT http://localhost:8000/api/admin/roles
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "TEST",
    "description": "更新权限"
}

### 删除权限
DELETE http://localhost:8000/api/admin/roles?id=TEST
Accept: application/json
Authorization: Bearer {{token}}

### 更改用户信息
PUT http://localhost:8000/api/users/info
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "avatar": "https://ixk.me/avatar-full.jpg"
}

### 发送验证码
POST http://localhost:8000/api/users/email
Accept: application/json
Authorization: Bearer {{token}}

### 更改邮箱
PUT http://localhost:8000/api/users/email
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "code": "IBRC4UFNA3",
    "email": "admin@ixk.me"
}

### 发送找回密码验证码
POST http://localhost:8000/api/reset-password/admin@ixk.me
Accept: application/json

### 找回密码
PUT http://localhost:8000/api/reset-password
Accept: application/json
Content-Type: application/json

{
    "code": "9413aa77-027d-4aac-9e78-78bdaa9efb2b",
    "password": "password"
}

### 添加关注
POST http://localhost:8000/api/follows
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user": 3
}

### 取消关注
DELETE http://localhost:8000/api/follows?user=3
Accept: application/json
Authorization: Bearer {{token}}

### 获取关注列表
GET http://localhost:8000/api/follows/1/following
Accept: application/json

### 获取被关注列表
GET http://localhost:8000/api/follows/3/follower
Accept: application/json

### 上传文件
POST http://localhost:8001/api/files
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pom.xml"
Content-Type: application/json

< ./pom.xml
--WebAppBoundary--

### 读取文件
GET http://localhost:8001/api/files/1234567890/a91db416-46b1-40c0-ad79-9ce9b0306a4e.xml

### 上传图片
POST http://localhost:8001/api/files
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer token.1706b23c-daaa-4ff5-bd50-54643d63aa7e

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: application/json

< D:/Pictures/1.jpg
--WebAppBoundary--

### 下载图片
GET http://localhost:8001/api/images/909356d9-e642-4a3f-a396-37e7a7382aac.jpg
Authorization: Bearer {{token}}

### 列出文件
GET http://localhost:8001/api/files?page=1&size=1
Authorization: Bearer {{token}}

###
GET http://localhost:8000/api/users/logged
Authorization: Bearer {{token}}

###
DELETE http://localhost:8000/api/users/exclude/8e6746fa-92f4-4d17-841d-3d40384220df
Authorization: Bearer {{token}}

### 获取工作区
GET http://localhost:8001/api/workspace
Authorization: Bearer {{token}}

### 增加工作区
POST http://localhost:8001/api/workspace
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Test",
    "description": "Description",
    "domain": "test",
    "icon": "https://ixk.me/bg.jpg"
}

> {% client.global.set("test_workspace_id", response.body.data.id); %}

### 修改工作区
PUT http://localhost:8001/api/workspace/{{test_workspace_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Description1"
}

### 删除工作区
DELETE http://localhost:8001/api/workspace/{{test_workspace_id}}
Authorization: Bearer {{token}}

### 获取笔记列表
GET http://localhost:8001/api/notes/elxu2uz71y
Authorization: Bearer {{token}}

### 获取笔记
GET http://localhost:8001/api/notes/elxu2uz71y/fe4o0pf0dd
Authorization: Bearer {{token}}

### 添加笔记
POST http://localhost:8001/api/notes/elxu2uz71y
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "TestNote",
    "content": "1234567890",
    "type": "note",
    "parent": "r52x9pi897"
}

### 更新笔记
PUT http://localhost:8001/api/notes/elxu2uz71y/fe4o0pf0dd
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "1234567890"
}

### 添加日志
POST http://localhost:8001/api/log
Authorization: Bearer token.1706b23c-daaa-4ff5-bd50-54643d63aa7e
Content-Type: application/json

{
    "type": "TEST",
    "method": "POST",
    "ip": "127.0.0.1",
    "user": "1234567890",
    "module": "hoshi-test",
    "operate": "public int java.lang.Integer.intValue()",
    "startTime": "2021-06-04T22:22:38.072398+08:00",
    "endTime": "2021-06-04T22:22:38.072398+08:00",
    "status": true,
    "message": "测试"
}
