server:
  port: ${PORT:8000}
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_FILE_SIZE:20MB}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: smtp
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.tls: ${MAIL_TLS}
      mail.smtp.starttls.enable: ${MAIL_STARTTLS}
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
springdoc:
  swagger-ui:
    path: /actuator/swagger-ui.html
  api-docs:
    path: /actuator/openapi
