apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          ports:
            - name: minio
              containerPort: 9000
              hostPort: 9000
            - name: minio-console
              containerPort: 9001
              hostPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: minio-data
          hostPath:
            path: /mnt/data/minio
