grafana:
  enabled: true
  adminPassword: password
  service:
    type: ClusterIP
promtail:
  enabled: true
loki:
  enabled: true
  service:
    type: ClusterIP
prometheus:
  enabled: true
  server:
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    service:
      type: ClusterIP
    persistentVolume:
      enabled: false
  alertmanager:
    persistentVolume:
      enabled: false
