grafana:
  enabled: true
  adminPassword: password
  service:
    type: NodePort
    nodePort: 30990
promtail:
  enabled: true
loki:
  enabled: true
  service:
    type: NodePort
    nodePort: 30081
prometheus:
  enabled: true
  server:
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    service:
      type: NodePort
      nodePort: 30991
    persistentVolume:
      enabled: false
  alertmanager:
    persistentVolume:
      enabled: false
