#
# Copyright (c) 2021, Otstar Lin (syfxlin@gmail.com). All Rights Reserved.
#
hoshi:
  version: 1.0
  name: Hoshi Note 接口文档
  description: 一个集各种神奇功能的云笔记
  author:
    name: Otstar Lin
    url: https://ixk.me
    email: syfxlin@gmail.com
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoshi_note?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
