apiVersion: v1
kind: Namespace
metadata:
  name: cockroach-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cockroach-operator
  namespace: helm
spec:
  repo: https://syfxlin.github.io/cockroach-operator
  chart: cockroach-operator
  targetNamespace: cockroach-system
