apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
  namespace: services
spec:
  dataStore:
    pvc:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "16Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 0.1
      memory: 100Mi
    limits:
      cpu: 1
      memory: 2Gi
  image:
    name: cockroachdb/cockroach:v21.2.5
  nodes: 3
  tlsEnabled: true
