server:
  port: 7600
spring:
  cloud:
    config:
      server:
        # 开发环境，如果是生产环境应使用 git
        native:
          search-locations: ${SPRING_CONFIG_LOCATIONS}
  security:
    user:
      name: hoshi-config
      password: ${SPRING_CONFIG_PASSWORD}
encrypt:
  key: ${SRPING_CONFIG_ENCRYPT_KEY}
management:
  endpoints:
    web:
      exposure:
        include: "*"
