### Token 登录
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

token={{token}}

> {% client.global.set("session_token", response.headers.valueOf("X-Auth-Token")); %}

### 上传文件
POST http://localhost:8002/files
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{session_token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.jpg"
Content-Type: image/png

< 1.jpg
--WebAppBoundary--

### 列出文件
GET http://localhost:8002/files
Accept: application/json
Authorization: Bearer {{session_token}}

> {% client.global.set("disk", response.body.data.records[0].disk); %}

### 删除文件
DELETE http://localhost:8002/files/{{disk}}
Accept: application/json
Authorization: Bearer {{session_token}}
