server:
  port: ${PORT:8000}
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  redis:
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}
    sentinel:
      master: mymaster
      nodes: ${REDIS_SENTINEL}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_FILE_SIZE:20MB}
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
springdoc:
  swagger-ui:
    path: /actuator/swagger-ui.html
  api-docs:
    path: /actuator/openapi
