# spring k8s 需要分配 ServiceAccount 才能正常进行服务发现和配置
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hoshi-note
  namespace: hoshi-note
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hoshi-note
  name: namespace-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: hoshi-note
  name: namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: hoshi-note
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
