apiVersion: v1
kind: Secret
metadata:
  name: hoshi-services
  namespace: hoshi-note
stringData:
  # 命名空间
  KUBERNETES_NAMESPACE: "hoshi-note"
  # 端口
  PORT: "8000"
  # MySQL 配置
  MYSQL_URL: "jdbc:mysql://tidb-tidb.services:4000/hoshi_note?serverTimezone=GMT%2B8"
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "<password>"
  # Redis 配置
  REDIS_SENTINEL: "rfs-redis.services:26379"
  REDIS_DATABASE: "0"
  REDIS_PASSWORD: "<password>"
  # Minio 配置
  MINIO_URL: "http://minio.services:9000"
  MINIO_BUCKET: "hoshi"
  MINIO_ACCESS_KEY: "hoshi_note"
  MINIO_SECRET_KEY: "<password>"
  # 邮件配置
  MAIL_HOST: "smtp.fastmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "no-reply@ixk.me"
  MAIL_USERNAME: "i@ixk.me"
  MAIL_PASSWORD: "<password>"
  MAIL_TLS: "true"
  MAIL_STARTTLS: "true"
  # RabbitMQ 配置
  RABBITMQ_USERNAME: "hoshi_note"
  RABBITMQ_PASSWORD: "<password>"
  RABBITMQ_HOST: "rabbitmq.services"
  RABBITMQ_PORT: "5672"
  # 上传文件最大大小
  MAX_FILE_SIZE: "20MB"
  # Pexels 图库
  PEXELS_TOKEN: "<token>"
