apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: hoshi-note
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hoshi-services
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hoshi-services
                  key: MINIO_SECRET_KEY
          ports:
            - name: minio
              containerPort: 9000
            - name: minio-console
              containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: hoshi-note
spec:
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000
      nodePort: 30910
    - name: minio-console
      port: 9001
      nodePort: 30911
  type: NodePort
