apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: monitoring
  namespace: helm
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      enabled: true
      adminPassword: password
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 3Gi
        accessModes:
          - ReadWriteMany
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
        accessModes:
          - ReadWriteMany
    prometheus:
      enabled: true
      server:
        global:
          scrape_interval: 15s
          scrape_timeout: 10s
          evaluation_interval: 15s
        persistentVolume:
          enabled: true
          storageClass: longhorn
          size: 5Gi
          accessModes:
            - ReadWriteMany
      alertmanager:
        persistentVolume:
          enabled: true
          storageClass: longhorn
          accessModes:
            - ReadWriteMany
