apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: monitoring
  namespace: helm
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      enabled: true
      adminPassword: password
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 3Gi
        accessModes:
          - ReadWriteMany
    prometheus:
      enabled: true
      prometheusSpec:
        scrapeInterval: "15s"
        scrapeTimeout: "10s"
        evaluationInterval: "15s"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 5Gi
              accessModes:
                - ReadWriteMany
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 5Gi
              accessModes:
                - ReadWriteMany
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: helm
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  targetNamespace: monitoring
  valuesContent: |-
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
        accessModes:
          - ReadWriteMany
