apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoshi-file
  namespace: hoshi-note
  labels:
    app: hoshi-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoshi-file
  template:
    metadata:
      name: hoshi-file
      labels:
        app: hoshi-file
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: hoshi-note
      containers:
        - name: hoshi-file
          image: ghcr.io/syfxlin/hoshi-note:latest
          imagePullPolicy: IfNotPresent
          command:
            - java
            - -jar
            - /app/hoshi-file-1.0-SNAPSHOT.jar
          envFrom:
            - secretRef:
                name: hoshi-services
          ports:
            - name: hoshi-file
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hoshi-file
  namespace: hoshi-note
spec:
  selector:
    app: hoshi-file
  ports:
    - name: hoshi-file
      port: 8000
  type: ClusterIP
