apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: hoshi-note
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteMany
