apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoshi-mail
  labels:
    app: hoshi-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoshi-mail
  template:
    metadata:
      name: hoshi-mail
      labels:
        app: hoshi-mail
    spec:
      containers:
        - name: hoshi-mail
          image: ghcr.io/syfxlin/hoshi-note:hoshi-mail
          imagePullPolicy: IfNotPresent
          command:
            - java
            - -jar
            - /app/hoshi-mail-1.0-SNAPSHOT.jar
          envFrom:
            - secretRef:
                name: hoshi-services
          ports:
            - name: hoshi-mail
              containerPort: 8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hoshi-mail
spec:
  selector:
    app: hoshi-mail
  ports:
    - name: hoshi-mail
      port: 8000
  type: ClusterIP
