apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-nginx-controller
  namespace: monitoring
  labels:
    release: monitoring
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    any: true
