apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobLabel: app.kubernetes.io/instance
  endpoints:
    - port: tcp-prometheus-servicemonitor
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  namespaceSelector:
    any: true
