apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobLabel: app.kubernetes.io/instance
  endpoints:
    - port: manager
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app.kubernetes.io/name: longhorn
  namespaceSelector:
    any: true
