apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cockroachdb
  namespace: monitoring
  labels:
    release: monitoring
spec:
  endpoints:
    - port: http
      path: /_status/vars
      interval: 15s
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
  namespaceSelector:
    any: true
