{
 "title": "Nginx Ingress Logs Analysis",
 "description": "Dashboard for Nginx Ingress (Loki)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({app_kubernetes_io_name=\"ingress-nginx\"}[$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({app_kubernetes_io_name=\"ingress-nginx\"}[$__interval])"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | geoip_country_code != \"\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_code) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | geoip_country_code != \"\" and  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | line_format \"➡️ {{.http_host}} {{.request_method}} {{.request_uri}} with HTTP status: {{.status}} \""
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th percentile of Request Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.95, {app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "max by (host) (max_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
       "legendFormat": "max latency"
      }
     ]
    },
    {
     "title": "HTTP status codes over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  __error__=\"\" [$__interval]))",
       "legendFormat": "HTTP Status {{status}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 HTTP Referers",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum by (http_referer) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [15m])))",
       "legendFormat": "{{http_referer}}"
      }
     ]
    },
    {
     "title": "Top 10 User Agents",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum by (http_user_agent) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  __error__=\"\" [15m])))"
      }
     ]
    },
    {
     "title": "Top 10 visitor IPs",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, sum by (remote_addr, geoip_country_code) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json |  __error__=\"\" [15m])))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top 10 Requested Pages",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, sum by (request_uri,http_host) (count_over_time({app_kubernetes_io_name=\"ingress-nginx\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | regexp \"stdout F (?P<query>.*)\" | line_format \"{{ .query }}\" | json | status = 200 and request_uri != \"/\" | __error__=\"\" [15m])))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    }
   ]
  }
 ]
}