{
 "title": "Redis",
 "description": "Dashboard for Redis",
 "tags": [ "redis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{pod=\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{pod=\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{pod=\"$pod\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{pod=\"$pod\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=\"$pod\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=\"$pod\"}) - sum (redis_db_keys_expiring{pod=\"$pod\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{pod=\"$pod\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{pod=\"$pod\"}"
    }
   ]
  }
 ]
}