apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoshi-mail
  namespace: hoshi-note
  labels:
    app: hoshi-mail
    prometheus: hoshi-note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoshi-mail
  template:
    metadata:
      name: hoshi-mail
      namespace: hoshi-note
      labels:
        app: hoshi-mail
        prometheus: hoshi-note
    spec:
      serviceAccountName: hoshi-note
      containers:
        - name: hoshi-mail
          image: ghcr.io/syfxlin/hoshi-note:latest
          imagePullPolicy: IfNotPresent
          command:
            - java
            - -jar
            - /app/hoshi-mail-1.0-SNAPSHOT.jar
          envFrom:
            - secretRef:
                name: hoshi-services
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hoshi-mail
  namespace: hoshi-note
spec:
  selector:
    app: hoshi-mail
  ports:
    - name: http
      port: 8000
  type: ClusterIP
