server:
  port: 7001
eureka:
  instance:
    hostname: hoshi-peer1
  client:
    fetch-registry: false
    register-with-eureka: false
#  client:
#    service-url:
#      defaultZone: http://hoshi-peer2:7002/eureka/
