server:
  port: 7500
spring:
  application:
    name: hoshi-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    instance-id: ${spring.application.name}:${random.int[1,100]}
management:
  endpoints:
    web:
      exposure:
        include: "*"
