apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hoshi-services
                  key: MYSQL_PASSWORD
          ports:
            - name: mysql
              containerPort: 3306
              hostPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mysql-data
          hostPath:
            path: /mnt/data/mysql
