name: Delete GitHub packages image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        type: string
        required: true
jobs:
  delete-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: syfxlin
          name: hoshi-note
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
