name: Publish Hoshi-Note
on:
  workflow_dispatch:
    inputs:
      service:
        description: "Publish service name"
        type: choice
        required: true
        options:
          - hoshi-gateway
          - hoshi-file
          - hoshi-mail
          - hoshi-note
          - hoshi-ums
jobs:
  publish-docker:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          cp deploy/${{ github.event.inputs.service }}/Dockerfile .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfxlin/hoshi-note
          tags: |
            type=raw,value=${{ github.event.inputs.service }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
